---
title: "Group Analysis"
author: ["Shixiang Wang", "Huimin Li", "Xuan Wang", "Minfang Song", "Xue-Song Liu (Corresponding author)"]
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
    self_contained: false
    mathjax: true
    lightbox: true
    gallery: true
    toc: 3
bibliography: ref.bib
link-citations: yes
---

```{r knitr_init_04, echo=FALSE}
library(knitr)
library(rmdformats)
## Global options
options(max.print = "75")
opts_chunk$set(
  echo = TRUE,
  comment = "#>",
  collapse = TRUE,
  cache = FALSE,
  dpi = 300,
  warning = FALSE,
  message = FALSE,
  tidy = "styler"
)
opts_knit$set(width = 75)
```


Load packages.

```{r, message=FALSE}
library(tidyverse)
library(sigminer)
```

Load the data.

```{r}
df.seqz = readRDS(file = "../output/PRAD_Merge_Info_CNV_from_sequenza.RData")
```

## Group comparison

```{r}
cols_to_features <- c(
  "IsMetastatic", "HasFusion", "Stage", "GleasonScore",
  "Age", 
  "total_mutation", "n_driver", "Ti_fraction", "Tv_fraction",
  "n_of_cnv", "n_of_amp", "n_of_del", "n_of_vchr", "cna_burden",
  "MATH", "cluster", "purity", "ploidy"
)

feature_type <- c(rep("ca", 4), rep("co", 14))
```

```{r}
df.seqz$GleasonScore = as.character(df.seqz$GleasonScore)
df.seqz$GleasonScore = factor(df.seqz$GleasonScore, levels = as.character(6:10))

df.seqz2 = df.seqz
df.seqz2$cnv_enrich_sig = ifelse(
  !is.na(df.seqz2$cnv_enrich_sig),
  paste(df.seqz2$cnv_enrich_sig, "dominant"),
  NA
)

grp.cnv <- get_group_comparison(
  df.seqz2,
  col_group = "cnv_enrich_sig", # or "cnv_group"
  cols_to_compare = cols_to_features,
  type = feature_type
)
```

```{r}
plot.cnv <- show_group_comparison(
  grp.cnv,
  xlab = NA,
  method = "anova",
  text_angle_x = 60,
  text_hjust_x = 1,
  legend_position_ca = "right",
  label.x.npc = "center", 
  label.y.npc = "top",
  label = "p.format",
  hjust = 0.5
)
```

```{r, fig.width=8, fig.height=6}
plot.cnv$ca_comb
```


```{r, fig.width=10, fig.height=10}
plot.cnv$co_comb
```


```{r}
df.seqz2$snv_enrich_sig = ifelse(
  !is.na(df.seqz2$snv_enrich_sig),
  paste(df.seqz2$snv_enrich_sig, "dominant"),
  NA
)

grp.snv <- get_group_comparison(
  df.seqz2,
  col_group = "snv_enrich_sig", # or "snv_group"
  cols_to_compare = cols_to_features,
  type = feature_type
)
```

```{r}
plot.snv <- show_group_comparison(
  grp.snv,
  xlab = NA,
  method = "anova",
  text_angle_x = 60,
  text_hjust_x = 1,
  legend_position_ca = "right",
  label.x.npc = "center", 
  label.y.npc = "top",
  label = "p.format",
  hjust = 0.5
)
```

```{r, fig.width=8, fig.height=6}
plot.snv$ca_comb
```


```{r, fig.width=9, fig.height=10}
plot.snv$co_comb
```

## Group mapping

```{r}
df.map = df.seqz[, c("sample_type",
                     "cnv_enrich_sig",
                     "snv_enrich_sig")] %>% 
  na.omit()
names(df.map) = c("Sample type", "Dominant CNV signature", "Dominant SNV signature")
```

```{r}
show_group_mapping(df.map, 
                   col_to_flow = "Sample type", 
                   cols_to_map = setdiff(colnames(df.map), "Sample type"),
                   fill_na = "NA", include_sig = TRUE)
```

